# Generated by Django 6.0.4 on 2026-05-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("color", models.CharField(blank=True, choices=[("red", "Red"), ("blue", "Blue"), ("green", "Green"), ("black", "Black"), ("white", "White")], default="", max_length=32)),
                ("size", models.CharField(blank=True, choices=[("XS", "XS"), ("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")], default="", max_length=8)),
                ("description", models.TextField(blank=True, default="")),
            ],
        ),
    ]
