# Generated by Django 6.0.4 on 2026-05-01 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceSchema",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TargetSchema",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TargetField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("is_enum", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="django_borg.targetschema",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("field", "Field"), ("value", "Value")], max_length=8)),
                ("polarity", models.CharField(choices=[("do", "Do"), ("dont", "Don't")], max_length=8)),
                ("pattern_type", models.CharField(choices=[("exact", "Exact"), ("regex", "Regex")], max_length=8)),
                ("source_pattern", models.CharField(max_length=512)),
                ("target", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_field",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required for value rules; null for field rules.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="django_borg.targetfield",
                    ),
                ),
                (
                    "target_schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="django_borg.targetschema",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FieldMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current_target", models.CharField(blank=True, default="", max_length=255)),
                ("confidence", models.FloatField(default=0.0)),
                ("total_weight", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_field", models.CharField(max_length=128)),
                (
                    "source_schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_mappings",
                        to="django_borg.sourceschema",
                    ),
                ),
                (
                    "target_schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_mappings",
                        to="django_borg.targetschema",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ValueMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current_target", models.CharField(blank=True, default="", max_length=255)),
                ("confidence", models.FloatField(default=0.0)),
                ("total_weight", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_value", models.CharField(max_length=512)),
                (
                    "target_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_mappings",
                        to="django_borg.targetfield",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("ai", "AI"), ("human", "Human")], max_length=16)),
                ("identifier", models.CharField(max_length=255)),
                ("weight", models.PositiveIntegerField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "identifier"),
                        name="borg_voter_unique_identifier_per_kind",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveBigIntegerField()),
                ("agreed_target", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="votes",
                        to="django_borg.voter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="django_borg.sourceschema",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("schema", "name"), name="borg_sourcefield_unique_per_schema"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="targetfield",
            constraint=models.UniqueConstraint(fields=("schema", "name"), name="borg_targetfield_unique_per_schema"),
        ),
        migrations.AddConstraint(
            model_name="fieldmapping",
            constraint=models.UniqueConstraint(
                fields=("source_schema", "source_field"),
                name="borg_fieldmapping_unique_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="valuemapping",
            constraint=models.UniqueConstraint(
                fields=("target_field", "source_value"),
                name="borg_valuemapping_unique_source",
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["content_type", "object_id"], name="borg_vote_target_idx"),
        ),
    ]
